### ISSUE TITLE
Main Chart does not show correct data

### ISSUE THREAD

**Issue by mullema** [sylvainjule/kirby-matomo#15]
The chart shows only data from "Today" correctly.
Matomo-Version: 3.9.1

Here's a screenshot from the matomo dashboard
![matomo](https://user-images.githubusercontent.com/46723734/57027828-c119a900-6c3d-11e9-8f2e-8ff29c168a79.PNG)

The api responses look reasonable to me. (I uploaded the json responses [here](https://www.moeli.com/github/matomo.zip))

and that's what the plugin in kirby looks like:
Today looks right.
![heute](https://user-images.githubusercontent.com/46723734/57027949-0a69f880-6c3e-11e9-96db-ce7578221a23.PNG)

7 days is wrong
![7days](https://user-images.githubusercontent.com/46723734/57027970-1786e780-6c3e-11e9-87c2-483d8b4304a6.PNG)

Month is actually correct...since it's the first day of the month today.
![month](https://user-images.githubusercontent.com/46723734/57027975-1a81d800-6c3e-11e9-9f0e-20de17141844.PNG)

the chart is ok, but the labels are undefined
![year](https://user-images.githubusercontent.com/46723734/57028492-844eb180-6c3f-11e9-9f2a-2be0ff8beab7.PNG)

![summary](https://user-images.githubusercontent.com/46723734/57027978-1c4b9b80-6c3e-11e9-97cf-6505a0997ba2.PNG)

**Comment by luxlogica** [comment]
I think part of the problem mentioned here is just inconsistency with the toggle LABELS — we have "This Year", "This Month", "Today", but "Last 7 Days", when it should probably just be "This Week" to be consistent with the rest. Ideally, it would be great to have all of the following options, separately:

* **This Year** (data counted from 1st Jan of current year)
* **This Month** (data counted from 1st of this month)
* **This Week** (data counted from last Sunday)
* **Today**

Then, separated by a little space:
* **Last 365 days** (or 'Last Year')
* **Last 30 days** (or 'Last Month')
* **Last 7 days** (or 'Last Week')

**Comment by luxlogica** [comment]
I just noticed that when we select 'This Year', all the months are labelled "January"...

<img width="990" alt="Screen Shot 2019-09-15 at 3 08 58 pm" src="https://user-images.githubusercontent.com/2994472/64916863-e3fec100-d7ca-11e9-9bd5-76f22fe80511.png">

Also perhaps worthwhile mentioning that Issue #11 should be re-opened...

**Comment by sylvainjule** [comment]
I cannot reproduce any of those. 🤷‍♂️

@mullema, is there a way for you to create credentials for me to try and debug with the data from your analytics? 

@luxlogica, can you try with the install you've set up for me and check if the issue exists. Because all works fine on my end.

The "Last 7 days" is intentional and should indeed fetch the last 7 days, not start on Sunday.

<img width="933" alt="Capture d’écran 2019-10-30 à 17 28 22" src="https://user-images.githubusercontent.com/14079751/67878258-53dac800-fb3b-11e9-9f10-2de65c68d325.png">

The "Last year" tab does show the correct months on my setup.

<img width="927" alt="Capture d’écran 2019-10-30 à 17 30 00" src="https://user-images.githubusercontent.com/14079751/67878294-605f2080-fb3b-11e9-928c-5db309d93758.png">

I do not wish to add any more options, trying to keep this simple and low-maintenance on my end.

**Comment by mullema** [comment]
@sylvainjule do you still need access to my analytics data?

**Comment by sylvainjule** [comment]
Only if latest release didn't fix those issues?

**Comment by mullema** [comment]
All issues from my post above are solved. 
A new one is, that the TODAY view has no x-axis labels. 

And svgs are no longer loaded. (But I am on Kirby 3.1.2 which had different/no real svg handling)
