### ISSUE TITLE
no visitors are displayed in matamo

### ISSUE THREAD

**Issue by techsupportkoeln** [sylvainjule/kirby-matomo#41]
I installed matamo and did a test with a standalone test.php page containing the tracking code generated by matamo.
Visitors from the test.php page are displayed in matamo.

I also added the configuration to /site/config/config.php:

return array(
     'sylvainjule.matomo.url' => 'http://your-matomo.url',
     'sylvainjule.matomo.id' => 'mywebsite',
     'sylvainjule.matomo.token' => 'token_auth',
);

of course with my values.

Is it correct to add this section at the very end of config.php, i.e. after the last "];"?

I also tried to include the code <?php echo snippet('matomo') ?> but I'm not sure where it belongs.

Do you have any idea what is wrong on my side?

**Comment by alexanderkogan** [comment]
Hi, did you figure this out?
I set it up like this to test it locally, but I'm using the cloud version of matomo instead of on-premise:
```
  'sylvainjust.matomo' => [
    'url' => 'https://domain.matomo.cloud/',
    'id' => 'id',
    'disableCookies' => true,
    'debug' => true,
  ],
```
and added this to the config php in the returned array:
```
<?php

return [
  ... other configuration...
  'sylvainjust.matomo' => [
    ...
  ],
];
```

I also tried setting the blacklist to [] and adding each field one by one like in the documentation:
```
<?php

return [
  ... other configuration...
  'sylvainjust.matomo.url' => 'https://domain.matomo.cloud/',
  'sylvainjust.matomo.id' => 'id',
  ...
];
```
but I can't see the hits in the matomo cloud.

Maybe this plugin doesn't support the cloud version?
Also I'm still on the free trial period, but that shouldn't be an issue, I hope.

**Comment by sylvainjule** [comment]
This is a long unattented issue (apologies),

@techsupportkoeln, your issue came from this:

> Is it correct to add this section at the very end of config.php, i.e. after the last "];"?

These lines must be inserted in the main config array (i.e. before the last `];`) as anything placed after this array won't be read.

@alexanderkogan the fact that you see `<!-- Kirby Matomo -->`means that one of [these requirements](https://github.com/sylvainjule/kirby-matomo/blob/f77d81e1351e06fb7aa6e5e62fedceef606cbd73/lib/matomo.php#L8) isn't fullfilled. The lines you pasted show `'sylvainjust.matomo'`, it should be `'sylvainjule.matomo'` instead.

I'm closing this, feel free to ask to reopen or open a new issue if the issue persists.
